---
- name: Check if the Dynatrace Web Server Agent installer is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_wsagent_role_name }}/files/linux/{{ dynatrace_wsagent_linux_installer_file_name }}"
  register: dynatrace_wsagent_installer_provided

- name: Fail if the Dynatrace Web Server Agent installer is not provided locally
  fail: msg="The Dynatrace Web Server Agent installer is not provided at {{ playbook_dir }}/roles/{{ dynatrace_wsagent_role_name }}/files/linux/{{ dynatrace_wsagent_linux_installer_file_name }}."
  when: not dynatrace_wsagent_installer_provided.stat.exists

- include: linux/install-dynatrace-user.yml
  when: dynatrace_wsagent_installer_provided.stat.exists

- include: linux/install-dynatrace-wsagent.yml
  when: dynatrace_wsagent_installer_provided.stat.exists
