---
- name: Check if the Dynatrace installer is provided locally
  local_action:
    module: stat
    path: "{{ playbook_dir }}/roles/{{ dynatrace_wsagent_role_name }}/files/linux/{{ dynatrace_wsagent_linux_installer_file_name }}"
  register: dynatrace_wsagent_installer_file_provided

- include: linux/install-dynatrace-user.yml
- include: linux/install-dynatrace-wsagent.yml
